<?php
/**
 * BindApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2.0
 * Contact: support@haproxy.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * BindApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BindApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createBind
     *
     * Add a new bind
     *
     * @param  \Swagger\Client\Model\Bind $body body (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     * @param  int $version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it&#x27;s own version. (optional)
     * @param  bool $force_reload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration. (optional, default to false)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Bind
     */
    public function createBind($body, $frontend, $transaction_id = null, $version = null, $force_reload = 'false')
    {
        list($response) = $this->createBindWithHttpInfo($body, $frontend, $transaction_id, $version, $force_reload);
        return $response;
    }

    /**
     * Operation createBindWithHttpInfo
     *
     * Add a new bind
     *
     * @param  \Swagger\Client\Model\Bind $body (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     * @param  int $version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it&#x27;s own version. (optional)
     * @param  bool $force_reload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration. (optional, default to false)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Bind, HTTP status code, HTTP response headers (array of strings)
     */
    public function createBindWithHttpInfo($body, $frontend, $transaction_id = null, $version = null, $force_reload = 'false')
    {
        $returnType = '\Swagger\Client\Model\Bind';
        $request = $this->createBindRequest($body, $frontend, $transaction_id, $version, $force_reload);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Bind',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Bind',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 0:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createBindAsync
     *
     * Add a new bind
     *
     * @param  \Swagger\Client\Model\Bind $body (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     * @param  int $version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it&#x27;s own version. (optional)
     * @param  bool $force_reload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration. (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createBindAsync($body, $frontend, $transaction_id = null, $version = null, $force_reload = 'false')
    {
        return $this->createBindAsyncWithHttpInfo($body, $frontend, $transaction_id, $version, $force_reload)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createBindAsyncWithHttpInfo
     *
     * Add a new bind
     *
     * @param  \Swagger\Client\Model\Bind $body (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     * @param  int $version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it&#x27;s own version. (optional)
     * @param  bool $force_reload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration. (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createBindAsyncWithHttpInfo($body, $frontend, $transaction_id = null, $version = null, $force_reload = 'false')
    {
        $returnType = '\Swagger\Client\Model\Bind';
        $request = $this->createBindRequest($body, $frontend, $transaction_id, $version, $force_reload);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createBind'
     *
     * @param  \Swagger\Client\Model\Bind $body (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     * @param  int $version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it&#x27;s own version. (optional)
     * @param  bool $force_reload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration. (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createBindRequest($body, $frontend, $transaction_id = null, $version = null, $force_reload = 'false')
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling createBind'
            );
        }
        // verify the required parameter 'frontend' is set
        if ($frontend === null || (is_array($frontend) && count($frontend) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $frontend when calling createBind'
            );
        }

        $resourcePath = '/services/haproxy/configuration/binds';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($frontend !== null) {
            $queryParams['frontend'] = ObjectSerializer::toQueryValue($frontend);
        }
        // query params
        if ($transaction_id !== null) {
            $queryParams['transaction_id'] = ObjectSerializer::toQueryValue($transaction_id);
        }
        // query params
        if ($version !== null) {
            $queryParams['version'] = ObjectSerializer::toQueryValue($version);
        }
        // query params
        if ($force_reload !== null) {
            $queryParams['force_reload'] = ObjectSerializer::toQueryValue($force_reload);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteBind
     *
     * Delete a bind
     *
     * @param  string $name Bind name (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     * @param  int $version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it&#x27;s own version. (optional)
     * @param  bool $force_reload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration. (optional, default to false)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteBind($name, $frontend, $transaction_id = null, $version = null, $force_reload = 'false')
    {
        $this->deleteBindWithHttpInfo($name, $frontend, $transaction_id, $version, $force_reload);
    }

    /**
     * Operation deleteBindWithHttpInfo
     *
     * Delete a bind
     *
     * @param  string $name Bind name (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     * @param  int $version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it&#x27;s own version. (optional)
     * @param  bool $force_reload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration. (optional, default to false)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteBindWithHttpInfo($name, $frontend, $transaction_id = null, $version = null, $force_reload = 'false')
    {
        $returnType = '';
        $request = $this->deleteBindRequest($name, $frontend, $transaction_id, $version, $force_reload);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 0:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteBindAsync
     *
     * Delete a bind
     *
     * @param  string $name Bind name (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     * @param  int $version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it&#x27;s own version. (optional)
     * @param  bool $force_reload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration. (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteBindAsync($name, $frontend, $transaction_id = null, $version = null, $force_reload = 'false')
    {
        return $this->deleteBindAsyncWithHttpInfo($name, $frontend, $transaction_id, $version, $force_reload)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteBindAsyncWithHttpInfo
     *
     * Delete a bind
     *
     * @param  string $name Bind name (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     * @param  int $version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it&#x27;s own version. (optional)
     * @param  bool $force_reload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration. (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteBindAsyncWithHttpInfo($name, $frontend, $transaction_id = null, $version = null, $force_reload = 'false')
    {
        $returnType = '';
        $request = $this->deleteBindRequest($name, $frontend, $transaction_id, $version, $force_reload);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteBind'
     *
     * @param  string $name Bind name (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     * @param  int $version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it&#x27;s own version. (optional)
     * @param  bool $force_reload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration. (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deleteBindRequest($name, $frontend, $transaction_id = null, $version = null, $force_reload = 'false')
    {
        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling deleteBind'
            );
        }
        // verify the required parameter 'frontend' is set
        if ($frontend === null || (is_array($frontend) && count($frontend) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $frontend when calling deleteBind'
            );
        }

        $resourcePath = '/services/haproxy/configuration/binds/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($frontend !== null) {
            $queryParams['frontend'] = ObjectSerializer::toQueryValue($frontend);
        }
        // query params
        if ($transaction_id !== null) {
            $queryParams['transaction_id'] = ObjectSerializer::toQueryValue($transaction_id);
        }
        // query params
        if ($version !== null) {
            $queryParams['version'] = ObjectSerializer::toQueryValue($version);
        }
        // query params
        if ($force_reload !== null) {
            $queryParams['force_reload'] = ObjectSerializer::toQueryValue($force_reload);
        }

        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getBind
     *
     * Return one bind
     *
     * @param  string $name Bind name (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\InlineResponse2009
     */
    public function getBind($name, $frontend, $transaction_id = null)
    {
        list($response) = $this->getBindWithHttpInfo($name, $frontend, $transaction_id);
        return $response;
    }

    /**
     * Operation getBindWithHttpInfo
     *
     * Return one bind
     *
     * @param  string $name Bind name (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\InlineResponse2009, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBindWithHttpInfo($name, $frontend, $transaction_id = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse2009';
        $request = $this->getBindRequest($name, $frontend, $transaction_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\InlineResponse2009',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 0:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getBindAsync
     *
     * Return one bind
     *
     * @param  string $name Bind name (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBindAsync($name, $frontend, $transaction_id = null)
    {
        return $this->getBindAsyncWithHttpInfo($name, $frontend, $transaction_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBindAsyncWithHttpInfo
     *
     * Return one bind
     *
     * @param  string $name Bind name (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBindAsyncWithHttpInfo($name, $frontend, $transaction_id = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse2009';
        $request = $this->getBindRequest($name, $frontend, $transaction_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBind'
     *
     * @param  string $name Bind name (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getBindRequest($name, $frontend, $transaction_id = null)
    {
        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling getBind'
            );
        }
        // verify the required parameter 'frontend' is set
        if ($frontend === null || (is_array($frontend) && count($frontend) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $frontend when calling getBind'
            );
        }

        $resourcePath = '/services/haproxy/configuration/binds/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($frontend !== null) {
            $queryParams['frontend'] = ObjectSerializer::toQueryValue($frontend);
        }
        // query params
        if ($transaction_id !== null) {
            $queryParams['transaction_id'] = ObjectSerializer::toQueryValue($transaction_id);
        }

        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getBinds
     *
     * Return an array of binds
     *
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\InlineResponse2008
     */
    public function getBinds($frontend, $transaction_id = null)
    {
        list($response) = $this->getBindsWithHttpInfo($frontend, $transaction_id);
        return $response;
    }

    /**
     * Operation getBindsWithHttpInfo
     *
     * Return an array of binds
     *
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\InlineResponse2008, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBindsWithHttpInfo($frontend, $transaction_id = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse2008';
        $request = $this->getBindsRequest($frontend, $transaction_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\InlineResponse2008',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 0:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getBindsAsync
     *
     * Return an array of binds
     *
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBindsAsync($frontend, $transaction_id = null)
    {
        return $this->getBindsAsyncWithHttpInfo($frontend, $transaction_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBindsAsyncWithHttpInfo
     *
     * Return an array of binds
     *
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBindsAsyncWithHttpInfo($frontend, $transaction_id = null)
    {
        $returnType = '\Swagger\Client\Model\InlineResponse2008';
        $request = $this->getBindsRequest($frontend, $transaction_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBinds'
     *
     * @param  string $frontend Parent frontend name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getBindsRequest($frontend, $transaction_id = null)
    {
        // verify the required parameter 'frontend' is set
        if ($frontend === null || (is_array($frontend) && count($frontend) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $frontend when calling getBinds'
            );
        }

        $resourcePath = '/services/haproxy/configuration/binds';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($frontend !== null) {
            $queryParams['frontend'] = ObjectSerializer::toQueryValue($frontend);
        }
        // query params
        if ($transaction_id !== null) {
            $queryParams['transaction_id'] = ObjectSerializer::toQueryValue($transaction_id);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation replaceBind
     *
     * Replace a bind
     *
     * @param  \Swagger\Client\Model\Bind $body body (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $name Bind name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     * @param  int $version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it&#x27;s own version. (optional)
     * @param  bool $force_reload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration. (optional, default to false)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\Bind
     */
    public function replaceBind($body, $frontend, $name, $transaction_id = null, $version = null, $force_reload = 'false')
    {
        list($response) = $this->replaceBindWithHttpInfo($body, $frontend, $name, $transaction_id, $version, $force_reload);
        return $response;
    }

    /**
     * Operation replaceBindWithHttpInfo
     *
     * Replace a bind
     *
     * @param  \Swagger\Client\Model\Bind $body (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $name Bind name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     * @param  int $version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it&#x27;s own version. (optional)
     * @param  bool $force_reload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration. (optional, default to false)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\Bind, HTTP status code, HTTP response headers (array of strings)
     */
    public function replaceBindWithHttpInfo($body, $frontend, $name, $transaction_id = null, $version = null, $force_reload = 'false')
    {
        $returnType = '\Swagger\Client\Model\Bind';
        $request = $this->replaceBindRequest($body, $frontend, $name, $transaction_id, $version, $force_reload);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Bind',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Bind',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 0:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation replaceBindAsync
     *
     * Replace a bind
     *
     * @param  \Swagger\Client\Model\Bind $body (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $name Bind name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     * @param  int $version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it&#x27;s own version. (optional)
     * @param  bool $force_reload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration. (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function replaceBindAsync($body, $frontend, $name, $transaction_id = null, $version = null, $force_reload = 'false')
    {
        return $this->replaceBindAsyncWithHttpInfo($body, $frontend, $name, $transaction_id, $version, $force_reload)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation replaceBindAsyncWithHttpInfo
     *
     * Replace a bind
     *
     * @param  \Swagger\Client\Model\Bind $body (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $name Bind name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     * @param  int $version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it&#x27;s own version. (optional)
     * @param  bool $force_reload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration. (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function replaceBindAsyncWithHttpInfo($body, $frontend, $name, $transaction_id = null, $version = null, $force_reload = 'false')
    {
        $returnType = '\Swagger\Client\Model\Bind';
        $request = $this->replaceBindRequest($body, $frontend, $name, $transaction_id, $version, $force_reload);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'replaceBind'
     *
     * @param  \Swagger\Client\Model\Bind $body (required)
     * @param  string $frontend Parent frontend name (required)
     * @param  string $name Bind name (required)
     * @param  string $transaction_id ID of the transaction where we want to add the operation. Cannot be used when version is specified. (optional)
     * @param  int $version Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it&#x27;s own version. (optional)
     * @param  bool $force_reload If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration. (optional, default to false)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function replaceBindRequest($body, $frontend, $name, $transaction_id = null, $version = null, $force_reload = 'false')
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling replaceBind'
            );
        }
        // verify the required parameter 'frontend' is set
        if ($frontend === null || (is_array($frontend) && count($frontend) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $frontend when calling replaceBind'
            );
        }
        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling replaceBind'
            );
        }

        $resourcePath = '/services/haproxy/configuration/binds/{name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($frontend !== null) {
            $queryParams['frontend'] = ObjectSerializer::toQueryValue($frontend);
        }
        // query params
        if ($transaction_id !== null) {
            $queryParams['transaction_id'] = ObjectSerializer::toQueryValue($transaction_id);
        }
        // query params
        if ($version !== null) {
            $queryParams['version'] = ObjectSerializer::toQueryValue($version);
        }
        // query params
        if ($force_reload !== null) {
            $queryParams['force_reload'] = ObjectSerializer::toQueryValue($force_reload);
        }

        // path params
        if ($name !== null) {
            $resourcePath = str_replace(
                '{' . 'name' . '}',
                ObjectSerializer::toPathValue($name),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
