<?php
/**
 * CookieTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2.0
 * Contact: support@haproxy.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CookieTest Class Doc Comment
 *
 * @category    Class
 * @description Cookie
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CookieTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Cookie"
     */
    public function testCookie()
    {
    }

    /**
     * Test attribute "domain"
     */
    public function testPropertyDomain()
    {
    }

    /**
     * Test attribute "dynamic"
     */
    public function testPropertyDynamic()
    {
    }

    /**
     * Test attribute "httponly"
     */
    public function testPropertyHttponly()
    {
    }

    /**
     * Test attribute "indirect"
     */
    public function testPropertyIndirect()
    {
    }

    /**
     * Test attribute "maxidle"
     */
    public function testPropertyMaxidle()
    {
    }

    /**
     * Test attribute "maxlife"
     */
    public function testPropertyMaxlife()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "nocache"
     */
    public function testPropertyNocache()
    {
    }

    /**
     * Test attribute "postonly"
     */
    public function testPropertyPostonly()
    {
    }

    /**
     * Test attribute "preserve"
     */
    public function testPropertyPreserve()
    {
    }

    /**
     * Test attribute "secure"
     */
    public function testPropertySecure()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }
}
