<?php
/**
 * HttpRequestRuleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2.0
 * Contact: support@haproxy.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * HttpRequestRuleTest Class Doc Comment
 *
 * @category    Class
 * @description HAProxy HTTP request rule configuration (corresponds to http-request directives)
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HttpRequestRuleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HttpRequestRule"
     */
    public function testHttpRequestRule()
    {
    }

    /**
     * Test attribute "acl_file"
     */
    public function testPropertyAclFile()
    {
    }

    /**
     * Test attribute "acl_keyfmt"
     */
    public function testPropertyAclKeyfmt()
    {
    }

    /**
     * Test attribute "auth_realm"
     */
    public function testPropertyAuthRealm()
    {
    }

    /**
     * Test attribute "capture_id"
     */
    public function testPropertyCaptureId()
    {
    }

    /**
     * Test attribute "capture_len"
     */
    public function testPropertyCaptureLen()
    {
    }

    /**
     * Test attribute "capture_sample"
     */
    public function testPropertyCaptureSample()
    {
    }

    /**
     * Test attribute "cond"
     */
    public function testPropertyCond()
    {
    }

    /**
     * Test attribute "cond_test"
     */
    public function testPropertyCondTest()
    {
    }

    /**
     * Test attribute "deny_status"
     */
    public function testPropertyDenyStatus()
    {
    }

    /**
     * Test attribute "hdr_format"
     */
    public function testPropertyHdrFormat()
    {
    }

    /**
     * Test attribute "hdr_match"
     */
    public function testPropertyHdrMatch()
    {
    }

    /**
     * Test attribute "hdr_name"
     */
    public function testPropertyHdrName()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "log_level"
     */
    public function testPropertyLogLevel()
    {
    }

    /**
     * Test attribute "path_fmt"
     */
    public function testPropertyPathFmt()
    {
    }

    /**
     * Test attribute "query_fmt"
     */
    public function testPropertyQueryFmt()
    {
    }

    /**
     * Test attribute "redir_code"
     */
    public function testPropertyRedirCode()
    {
    }

    /**
     * Test attribute "redir_option"
     */
    public function testPropertyRedirOption()
    {
    }

    /**
     * Test attribute "redir_type"
     */
    public function testPropertyRedirType()
    {
    }

    /**
     * Test attribute "redir_value"
     */
    public function testPropertyRedirValue()
    {
    }

    /**
     * Test attribute "spoe_engine"
     */
    public function testPropertySpoeEngine()
    {
    }

    /**
     * Test attribute "spoe_group"
     */
    public function testPropertySpoeGroup()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "uri_fmt"
     */
    public function testPropertyUriFmt()
    {
    }

    /**
     * Test attribute "var_expr"
     */
    public function testPropertyVarExpr()
    {
    }

    /**
     * Test attribute "var_name"
     */
    public function testPropertyVarName()
    {
    }

    /**
     * Test attribute "var_scope"
     */
    public function testPropertyVarScope()
    {
    }
}
