<?php
/**
 * ServerSwitchingRuleApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 2.0
 * Contact: support@haproxy.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ServerSwitchingRuleApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ServerSwitchingRuleApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createServerSwitchingRule
     *
     * Add a new Server Switching Rule.
     *
     */
    public function testCreateServerSwitchingRule()
    {
    }

    /**
     * Test case for deleteServerSwitchingRule
     *
     * Delete a Server Switching Rule.
     *
     */
    public function testDeleteServerSwitchingRule()
    {
    }

    /**
     * Test case for getServerSwitchingRule
     *
     * Return one Server Switching Rule.
     *
     */
    public function testGetServerSwitchingRule()
    {
    }

    /**
     * Test case for getServerSwitchingRules
     *
     * Return an array of all Server Switching Rules.
     *
     */
    public function testGetServerSwitchingRules()
    {
    }

    /**
     * Test case for replaceServerSwitchingRule
     *
     * Replace a Server Switching Rule.
     *
     */
    public function testReplaceServerSwitchingRule()
    {
    }
}
